# Site settings
title: SP Blog
SEOTitle: SP Blog
header-img: img/home-sp-hd-2.jpg
email: pradhan.shrijal@gmail.com
description: "Blog about my Work, Projects and Travels."
keyword: "Shrijal, SP Blog, Robotics, Perception"
url: "https://pradhanshrijal.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/pradhanshrijal/pradhanshrijal.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Currently working on Perception and Simulation."
sidebar-avatar: /img/sp-formal.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
github_username:    pradhanshrijal
linkedin_username:   pradhanshrijal




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
future: true
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 046499b6e5d22e165542                            #生成的clientID
  clientSecret: ccf937102dac5122ed6409310c60bce6da2fefa0    #生成的clientSecret
  repo: pradhanshrijal.github.io    #仓库名称
  owner: pradhanshrijal    #github用户名
  admin: pradhanshrijal
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
references: [
    {
        title: "CowCow",
        href: "http://cowcowabenteuer.github.io"
    },
    {
        title: "DLR-SE",
        href: "https://www.dlr.de/se/"
    },
    {
        title: "Hux Blog",
        href: "https://github.com/Huxpro/huxpro.github.io"
    }
]
